### ISSUE TITLE
Problem while initializing node

### ISSUE THREAD

**Issue by Jamaslab** [ipa320/ipa_canopen#74]
Hello,
I managed to compile the ipa_canopen without ROS. When I launch any program I get the following error:

```
Interrupt motion with Ctrl-C
Resetting communication with the devices
Initializing test_chain
Waiting for Node: 3 to become available
Node: 3 is not ready for operation. Please check for eventual problems.
```

The PEAK adapter seems to work correctly (red led blinking fast). Any possible solutions?

Giacomo

**Comment by thiagodefreitas** [comment]
Hi @Jamaslab Please, if possible, use https://github.com/ipa320/ros_canopen as there is no more support to ipa_canopen.

**Comment by Jamaslab** [comment]
I really need a standalone software, I'm not allowed to use ROS.

Giacomo
