### ISSUE TITLE
Trigger service is removed from cob_srvs but is used here

### ISSUE THREAD

**Issue by VahidAminZ** [ipa320/ipa_canopen#75]
The service is removed from the cob_srvs but is used here for example:
https://github.com/ipa320/ipa_canopen/blob/indigo_dev/ipa_canopen_ros/src/ipa_canopen_ros.cpp#L66

**Comment by ipa-fmw** [comment]
ipa_canopen is deprecated in favour of ros_canopen (http://wiki.ros.org/ros_canopen) which is independent of cob repositories.
Code: https://github.com/ros-industrial/ros_canopen
