### ISSUE TITLE
ipa_canopen requires previous release of cob_srvs

### ISSUE THREAD

**Issue by copplestone** [ipa320/ipa_canopen#76]
Got an error when running catkin_make. ([see original question here](http://answers.ros.org/question/227840/cant-build-ipa_canopen/)).

**Comment by ipa-fxm** [comment]
As @ipa-mdl [answered](http://answers.ros.org/question/227840/cant-build-ipa_canopen/?answer=227886#post-id-227886)

 > ipa_canopen ist not supported on indigo (we will remove the branches soon).
 > 
 > LWA3 is using schunk_powercube_chain, LWA4 was migrated to ros_canopen with example configs in schunk_robots. In both cases you don't need ipa_canopen.
